### ISSUE TITLE
doesn't uninstall cleanly

### ISSUE THREAD

**Issue by fulv** [collective/collective.weather#7]
I uninstalled collective.weather from portal_quickinstaller, and removed it from buildout.  Now, when I restart the instance I get: 

2012-09-16 10:59:07 ERROR Zope.SiteErrorLog 1347818347.20.901586274708 http://localhost:8081/Plone
Traceback (innermost last):
  Module ZPublisher.Publish, line 115, in publish
  Module ZPublisher.BaseRequest, line 437, in traverse
  Module ZPublisher.BeforeTraverse, line 97, in **call**
  Module Products.CMFCore.PortalObject, line 75, in **before_publishing_traverse**
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module plone.browserlayer.layer, line 15, in mark_layer
  Module zope.component._api, line 179, in getAllUtilitiesRegisteredFor
  Module zope.component.registry, line 176, in getAllUtilitiesRegisteredFor
  Module ZODB.Connection, line 860, in setstate
  Module ZODB.Connection, line 914, in _setstate
  Module ZODB.serialize, line 612, in setGhostState
  Module ZODB.serialize, line 605, in getState
  Module DateTime.DateTime, line 1872, in _dt_reconstructor
  Module copy_reg, line 48, in _reconstructor
TypeError: ('object.__new__(WeatherUtility) is not safe, use Persistence.Persistent.**new**()', <function _dt_reconstructor at 0x1027f4938>, (<class 'collective.weather.weather_utility.WeatherUtility'>, <type 'object'>, None))
2012-09-16 10:59:07 ERROR ZODB.Connection Couldn't load state for 0x0dd6
Traceback (most recent call last):
  File "/Users/fulvio/plone/Plone4.2/buildout-cache/eggs/ZODB3-3.10.5-py2.7-macosx-10.4-x86_64.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/Users/fulvio/plone/Plone4.2/buildout-cache/eggs/ZODB3-3.10.5-py2.7-macosx-10.4-x86_64.egg/ZODB/Connection.py", line 914, in _setstate
    self._reader.setGhostState(obj, p)
  File "/Users/fulvio/plone/Plone4.2/buildout-cache/eggs/ZODB3-3.10.5-py2.7-macosx-10.4-x86_64.egg/ZODB/serialize.py", line 612, in setGhostState
    state = self.getState(pickle)
  File "/Users/fulvio/plone/Plone4.2/buildout-cache/eggs/ZODB3-3.10.5-py2.7-macosx-10.4-x86_64.egg/ZODB/serialize.py", line 605, in getState
    return unpickler.load()
  File "/Users/fulvio/plone/Plone4.2/buildout-cache/eggs/DateTime-2.12.7-py2.7.egg/DateTime/DateTime.py", line 1872, in _dt_reconstructor
    return orig_reconstructor(cls, base, state)
  File "/Users/fulvio/plone/Plone4.2/Python-2.7/lib/python2.7/copy_reg.py", line 48, in _reconstructor
    obj = object.__new__(cls)
TypeError: ('object.**new**(WeatherUtility) is not safe, use Persistence.Persistent.**new**()', <function _dt_reconstructor at 0x1027f4938>, (<class 'collective.weather.weather_utility.WeatherUtility'>, <type 'object'>, None))

**Comment by fulv** [comment]
Actually, I'm not sure if that's due to something I did.  I just tried again on a clean site, and it seems to uninstall fine.

**Comment by hvelarde** [comment]
what did you did? ;-)

**Comment by fulv** [comment]
I don't know ;).  My guess is that I _thought_ I had uninstalled collective.weather, but maybe I just re-ran buildout after taking it out of the eggs, and started the instance with c.w still installed but without the egg.

**Comment by hvelarde** [comment]
ok; if it happens again and you can provide more information we will reopen it ;-)

**Comment by fulv** [comment]
This time, I'm sure I uninstalled the product collective.weather from the ZMI portal_quickinstaller.  Then I removed it from the bin/instance script and removed the 00n-collective.weather-configure.zcml from parts/instance/etc/package-includes.  when I restart and navigate to the site, I get this:

2012-11-25 18:31:56 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/usr/local/zope/prod/Zope-2.13.15/plone4.2/eggs/Zope2-2.13.15-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in **init**
    response=b)
  File "/usr/local/zope/prod/Zope-2.13.15/plone4.2/eggs/Zope2-2.13.15-py2.7.egg/ZPublisher/Publish.py", line 443, in publish_module
    environ, debug, request, response)
  File "/usr/local/zope/prod/Zope-2.13.15/plone4.2/eggs/Zope2-2.13.15-py2.7.egg/ZPublisher/Publish.py", line 264, in publish_module_standard
    if request is not None: request.close()
  File "/usr/local/zope/prod/Zope-2.13.15/plone4.2/eggs/Zope2-2.13.15-py2.7.egg/ZPublisher/BaseRequest.py", line 218, in close
    notify(EndRequestEvent(None, self))
  File "/usr/local/zope/prod/Zope-2.13.15/plone4.2/eggs/zope.event-3.5.2-py2.7.egg/zope/event/**init**.py", line 31, in notify
    subscriber(event)
  File "/usr/local/zope/prod/Zope-2.13.15/plone4.2/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/usr/local/zope/prod/Zope-2.13.15/plone4.2/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/usr/local/zope/prod/Zope-2.13.15/plone4.2/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/usr/local/zope/prod/Zope-2.13.15/plone4.2/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 914, in _setstate
    self._reader.setGhostState(obj, p)
  File "/usr/local/zope/prod/Zope-2.13.15/plone4.2/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/serialize.py", line 612, in setGhostState
    state = self.getState(pickle)
  File "/usr/local/zope/prod/Zope-2.13.15/plone4.2/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/serialize.py", line 605, in getState
    return unpickler.load()
  File "/usr/local/zope/prod/Zope-2.13.15/lib/python2.7/copy_reg.py", line 48, in _reconstructor
    obj = object.__new__(cls)
TypeError: ('object.**new**(WeatherUtility) is not safe, use Persistence.Persistent.**new**()', <function _reconstructor at 0x7f70810c2ed8>, (<class 'collective.weather.weather_utility.WeatherUtility'>, <type 'object'>, None))

**Comment by hvelarde** [comment]
thanks for your feedback; @flecox @frapell who wrote this utility? could you please check it out?

**Comment by hvelarde** [comment]
you where totally right, @fulv; I think making this a local persistent utility was a bad design decision.

I hope you haven't tested this on a production site :-)

in any case, you can read the section dedicated to **componentregistry.xml** on [How to make your Plone add-on products uninstall cleanly](http://blog.keul.it/2013/05/how-to-make-your-plone-add-on-products.html). May the Force be with you.

**Comment by fulv** [comment]
It was a production site :(, but fortunately it was small, so I restarted
from scratch and copied all content manually.

Thanks!

## 

Fulvio
